### ISSUE TITLE
hello,i ' ve   already ready your text comparer. can i ask some questions 

### ISSUE THREAD

**Issue by cheshicheng** [zyfxn/text-comparer#1]
hello,clever boy,
i am from china ,i ' ve   already ready your text comparer.
but some places,i cannot understand them. 
for example,the class LeafSet.
i also find a bug in the project through my test.
can i communicate with you to discuss this questions?
I would appreciate it if you could contact my email address.
Mailbox: 576700810@163.com

**Comment by zyfxn** [comment]
hi,
i send you an email.
